window.DANU_CONFIG = {
    shopName: "Danu Multi Shop",
    shopTagline: "Fresh groceries in Mallavi",
    logoPath: "./images/logo.png",
    adminUsername: "admin",
    adminPassword: "admin123",
    whatsappNumber: "94771234567",
    storageKey: "danu-products",
    profileStorageKey: "danu-profile",
    products: [
        {
            id: "spinach",
            section: "today",
            name: "Fresh Spinach Bundle",
            category: "Fresh Vegetables",
            description: "Crisp spinach for salads, rice, and quick home cooking.",
            imageText: "🥬",
            price: "Rs. 75",
            originalPrice: "Rs. 100",
            discount: "25% OFF",
            footerLeft: "Visit our store",
            footerRight: "Today"
        },
        {
            id: "apple",
            section: "today",
            name: "Red Apples (1kg)",
            category: "Fresh Fruits",
            description: "Juicy, sweet red apples selected for everyday snacking.",
            imageText: "🍎",
            price: "Rs. 210",
            originalPrice: "Rs. 300",
            discount: "30% OFF",
            footerLeft: "Fresh stock",
            footerRight: "1kg"
        },
        {
            id: "carrot",
            section: "today",
            name: "Fresh Carrots (1kg)",
            category: "Fresh Vegetables",
            description: "Crunchy carrots for curries, soups, salads, and juice.",
            imageText: "🥕",
            price: "Rs. 80",
            originalPrice: "Rs. 100",
            discount: "20% OFF",
            footerLeft: "Fresh stock",
            footerRight: "1kg"
        },
        {
            id: "milk",
            section: "today",
            name: "Fresh Milk (1L)",
            category: "Daily Essentials",
            description: "Pure pasteurized milk for tea, breakfast, and baking.",
            imageText: "🥛",
            price: "Rs. 127.50",
            originalPrice: "Rs. 150",
            discount: "15% OFF",
            footerLeft: "Daily essential",
            footerRight: "1L"
        },
        {
            id: "orange",
            section: "week",
            name: "Fresh Oranges (1kg)",
            category: "Fresh Fruits",
            description: "Vitamin-rich oranges for juice, snacks, and lunchboxes.",
            imageText: "🍊",
            price: "Rs. 130",
            originalPrice: "Rs. 200",
            discount: "35% OFF",
            footerLeft: "Week deal",
            footerRight: "1kg",
            startDate: "",
            endDate: ""
        },
        {
            id: "broccoli",
            section: "week",
            name: "Fresh Broccoli (500g)",
            category: "Fresh Vegetables",
            description: "Green broccoli for healthy stir-fries and family meals.",
            imageText: "🥦",
            price: "Rs. 90",
            originalPrice: "Rs. 150",
            discount: "40% OFF",
            footerLeft: "Week deal",
            footerRight: "500g",
            startDate: "",
            endDate: ""
        },
        {
            id: "onion",
            section: "week",
            name: "Yellow Onions (1kg)",
            category: "Fresh Vegetables",
            description: "Premium onions for curries, sambols, and everyday cooking.",
            imageText: "🧅",
            price: "Rs. 80",
            originalPrice: "Rs. 100",
            discount: "20% OFF",
            footerLeft: "Kitchen staple",
            footerRight: "1kg",
            startDate: "",
            endDate: ""
        },
        {
            id: "honey",
            section: "week",
            name: "Pure Honey (500ml)",
            category: "Household Items",
            description: "Natural honey for tea, toast, desserts, and wellness routines.",
            imageText: "🍯",
            price: "Rs. 375",
            originalPrice: "Rs. 500",
            discount: "25% OFF",
            footerLeft: "Natural choice",
            footerRight: "500ml",
            startDate: "",
            endDate: ""
        },
        {
            id: "rice-special",
            section: "special",
            name: "Basmati Rice (5kg)",
            category: "Food Staples",
            description: "Premium rice for family meals and special cooking.",
            imageText: "🍚",
            price: "Rs. 750",
            originalPrice: "Rs. 900",
            discount: "Special",
            footerLeft: "Best value",
            footerRight: "5kg",
            startDate: "",
            endDate: ""
        }
    ]
};
